apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: asadhanif3188
spec:
  profile:
    # Intentional no displayName for testing
    email: asadhanif3188@gmail.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: breanna.davison
spec:
  profile:
    # Intentional no displayName for testing
    email: breanna-davison@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [development]
